HW_Lesson_02
Krab-35/Django_Framework_GB pull request #2
Opened 2021-08-14 17:57 UTC by Krab-35

2021-08-16 11:06 UTC, Vokler requested changes

2021-08-16 11:06 UTC, Vokler commented on products/views.py
> +    context = load_json()
В json файле не нужно хранить весь контекст, а только список продуктов. json файл в этом случае пока выступает у нас некой БД. А такие переменные как title лучше держать непосредственно в context

2021-08-16 12:12 UTC, Krab-35 commented on products/views.py
> +    context = load_json()
Валерий, код поправил, в json-файле теперь храниться только список продуктов

2021-08-17 12:17 UTC, Vokler approved these changes

2021-08-17 12:17 UTC, merged