HW_Lesson_07
Krab-35/Django_Framework_GB pull request #7
Opened 2021-09-03 01:26 UTC by Krab-35

2021-09-03 08:34 UTC, Vokler requested changes

2021-09-03 08:34 UTC, Vokler commented on admins/views.py
> +        else:
У вас блок else стоит не на тот if (сдвинуть назад нужно).
А context вообще вынести за все условия.

2021-09-03 14:27 UTC, Krab-35 commented on admins/views.py
> +        else:
@Vokler, спасибо, увидел!
Внес все правки, сделал реализацию удаления, а так же обработку is_active через checkbox

2021-09-06 14:40 UTC, Vokler approved these changes

2021-09-06 14:40 UTC, merged